name: "Smart Sofar Node-RED"
version: "0.1.0"
slug: smart-sofar
description: "Node-RED Sofar Solar bridge to MQTT (RS485 minimal version)"

arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

startup: services
boot: auto
init: false
uart: true
homeassistant_api: true

map:
  - type: addon_config
    read_only: false

devices:
  - /dev/serial/by-id:/dev/serial/by-id:rwm

ports:
  1892/tcp: 1892

panel_icon: mdi:solar-power

options:

  ##################################
  # INVERTER 1
  ##################################

  inv1_serial_port: "/dev/serial/by-id/CHANGE-ME-1"
  inv1_modbus_slave_id: 1
  inv1_modbus_baudrate: 9600
  inv1_model: "HYD6000EP"

  ##################################
  # INVERTER 2
  ##################################

  inv2_serial_port: ""
  inv2_modbus_slave_id: 1
  inv2_modbus_baudrate: 9600
  inv2_model: "HYD6000EP"

  ##################################
  # INVERTER 3
  ##################################

  inv3_serial_port: ""
  inv3_modbus_slave_id: 1
  inv3_modbus_baudrate: 9600
  inv3_model: "HYD6000EP"

  ##################################
  # MQTT
  ##################################

  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  mqtt_prefix: "sofar"

  ##################################
  # TIMEZONE
  ##################################

  timezone_mode: "Europe/Paris"
  timezone_custom: "UTC"

schema:

  ##################################
  # INVERTER 1
  ##################################

  inv1_serial_port: str
  inv1_modbus_slave_id: int(1,247)
  inv1_modbus_baudrate: list(9600|19200|38400|57600|115200)
  inv1_model: str?

  ##################################
  # INVERTER 2
  ##################################

  inv2_serial_port: str?
  inv2_modbus_slave_id: int(1,247)
  inv2_modbus_baudrate: list(9600|19200|38400|57600|115200)
  inv2_model: str?

  ##################################
  # INVERTER 3
  ##################################

  inv3_serial_port: str?
  inv3_modbus_slave_id: int(1,247)
  inv3_modbus_baudrate: list(9600|19200|38400|57600|115200)
  inv3_model: str?

  ##################################
  # MQTT
  ##################################

  mqtt_host: str
  mqtt_port: int(1,65535)
  mqtt_user: str?
  mqtt_pass: password?
  mqtt_prefix: str?

  ##################################
  # TIMEZONE
  ##################################

  timezone_mode: list(
    Europe/Paris|
    Europe/Berlin|
    Europe/Brussels|
    Europe/Madrid|
    Europe/Rome|
    Europe/London|
    America/New_York|
    America/Chicago|
    America/Los_Angeles|
    America/Montreal|
    Asia/Dubai|
    Asia/Tokyo|
    Australia/Sydney|
    CUSTOM
  )

  timezone_custom: str?
